# Spatial-Temporal Geographic Objects
EXTENSION = postgist

# Files that will be installed under prefix/share/postgist
DATA = postgist--0.1.0.sql

# Build based on pg_config framework
PG_CONFIG = pg_config

PGXS := $(shell $(PG_CONFIG) --pgxs)

include $(PGXS)
